name: e_book_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

    # https://ebookapp-437be.firebaseapp.com/__/auth/handler  => facebookId
    # ca-app-pub-9595262426417185~3918804299                  => admobId/mtz
    # ca-app-pub-9595262426417185/5338863029                  => unitId



  cupertino_icons: ^1.0.2
  # for statManagement
  get: ^4.6.6
  # for Image
  flutter_svg: ^2.0.10+1
  # for storeData in Local
  shared_preferences: ^2.2.2
  # for intro Screen
  introduction_screen: ^3.1.12
  # for Integrating firebase
  firebase_core: ^2.27.0
  # for Handling firebase authentication_
  firebase_auth: ^4.16.0
  # for accessing firebase storage upload file
  firebase_storage: ^11.6.9
  # for google Login
  google_sign_in: ^6.2.1
  # for fb Login
  flutter_facebook_auth: ^6.1.1
  # for Image Slider
  carousel_slider: ^4.2.1
  # for image dots show
  dots_indicator: ^2.1.2
  # for PdfViewer
  syncfusion_flutter_pdfviewer: ^23.2.4
  # for Play Youtube Video
  youtube_player_iframe: ^4.0.4
  # for Play Youtube Video
  youtube_player_flutter: ^9.0.0
  # for some sharing files and links etc...
  share_plus: ^7.2.2
  # for image pick
  image_picker: ^1.0.7
  # for more text show
  flutter_expandable_text: ^1.0.0
  # for app rating
  in_app_review: ^2.0.9
  # for show indicator
  smooth_page_indicator: ^1.1.0
  # for network image show
  cached_network_image: ^3.3.1
  loading_animation_widget: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/logo/
    - assets/icons/
    - assets/pdf/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
